/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "hostip": {                                       "en": "Host IP for multicast",                            "de": "IP adresse für Multicast",                         "ru": "IP хоста",                                         "pt": "IP do host",                                       "nl": "Host-IP",                                          "fr": "IP de l'hôte",                                     "it": "IP host",                                          "es": "IP del anfitrión",                                 "pl": "Adres IP hosta",                                   "zh-cn": "主机 IP"},
    "motionblinds adapter settings": {                "en": "Adapter settings for motionblinds",                "de": "Adaptereinstellungen für motionblinds",            "ru": "Настройки адаптера для motionblinds",              "pt": "Configurações do adaptador para motionblinds",     "nl": "Adapterinstellingen voor motionblinds",            "fr": "Paramètres d'adaptateur pour motionblinds",        "it": "Impostazioni dell'adattatore per motionblinds",    "es": "Ajustes del adaptador para motionblinds",          "pl": "Ustawienia adaptera dla motionblinds",             "zh-cn": "motionblinds的适配器设置"},
    "timeout": {                                      "en": "Timeout (seconds)",                                "de": "Zeitüberschreitung (Sekunden)",                    "ru": "Время ожидания (секунды)",                         "pt": "Tempo limite (segundos)",                          "nl": "Time-out (seconden)",                              "fr": "Délai d'attente (secondes)",                       "it": "Timeout (secondi)",                                "es": "Tiempo de espera (segundos)",                      "pl": "Limit czasu (sekundy)",                            "zh-cn": "超时（秒）"},
    "token": {                                        "en": "Accesstoken",                                      "de": "Zugangstoken",                                     "ru": "Токен доступа",                                    "pt": "token de acesso",                                  "nl": "Toegangstoken",                                    "fr": "Jeton d'accès",                                    "it": "Token di accesso",                                 "es": "token de acceso",                                  "pl": "Accesstoken",                                      "zh-cn": "访问令牌"},
};